<?php
/**
 * Flatpickr-based date picker with faded styling for unavailable dates.
 */

function legalpro_render_availability_date_picker_assets(): void
{
    static $rendered = false;
    if ($rendered) {
        return;
    }
    $rendered = true;

    echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">' . "\n";
    echo '<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>' . "\n";
}

function legalpro_render_availability_date_picker_styles(): void
{
    static $rendered = false;
    if ($rendered) {
        return;
    }
    $rendered = true;

    echo '<style>'
        . '.legalpro-date-picker-wrap{position:relative;}'
        . '.legalpro-date-picker-wrap .flatpickr-input.form-control{background-color:#fff;color:#344767;}'
        . '.flatpickr-calendar{width:268px!important;font-size:13px;line-height:1.2;padding:2px 0 6px;}'
        . '.flatpickr-days,.dayContainer{width:268px!important;min-width:268px!important;max-width:268px!important;}'
        . '.flatpickr-day{max-width:34px;height:34px;line-height:34px;font-size:12.5px;}'
        . '.flatpickr-current-month{font-size:14px!important;font-weight:600;height:30px;padding-top:4px;display:flex;align-items:center;justify-content:center;gap:4px;}'
        . '.flatpickr-current-month .flatpickr-monthDropdown-months{appearance:auto;-webkit-appearance:auto;-moz-appearance:auto;background:#fff;color:#344767!important;font-size:14px;font-weight:600;font-family:inherit;padding:2px 20px 2px 6px;border:1px solid #d2d6da;border-radius:6px;cursor:pointer;max-width:118px;}'
        . '.flatpickr-current-month .flatpickr-monthDropdown-months option{background:#fff;color:#1e293b;font-size:14px;font-weight:500;}'
        . '.flatpickr-current-month input.cur-year{color:#344767!important;background:#fff;font-size:14px;font-weight:600;border:1px solid #d2d6da;border-radius:6px;padding:2px 4px;}'
        . '.flatpickr-day.legalpro-day-unavailable,.flatpickr-day.flatpickr-disabled.legalpro-day-unavailable{text-decoration:none!important;color:#94a3b8!important;background:transparent!important;border-color:transparent!important;opacity:.38;cursor:default;pointer-events:none;}'
        . '.flatpickr-day.legalpro-day-unavailable:hover,.flatpickr-day.flatpickr-disabled.legalpro-day-unavailable:hover{background:transparent!important;color:#94a3b8!important;opacity:.38;}'
        . 'body.legalpro-dark-mode .legalpro-date-picker-wrap .flatpickr-input.form-control,'
        . '.legalpro-flatpickr-dark .legalpro-date-picker-wrap .flatpickr-input.form-control{background-color:#1e293b;color:#e2e8f0;border-color:rgba(255,255,255,.12);}'
        . 'body.legalpro-dark-mode .flatpickr-calendar,.legalpro-flatpickr-dark.flatpickr-calendar{background:#1e293b;border-color:rgba(255,255,255,.12);box-shadow:0 12px 32px rgba(0,0,0,.45);}'
        . 'body.legalpro-dark-mode .flatpickr-months,.legalpro-flatpickr-dark .flatpickr-months{background:#1e293b;}'
        . 'body.legalpro-dark-mode .flatpickr-current-month,.legalpro-flatpickr-dark .flatpickr-current-month{color:#f1f5f9;}'
        . 'body.legalpro-dark-mode .flatpickr-current-month .flatpickr-monthDropdown-months,'
        . 'body.legalpro-dark-mode .flatpickr-current-month input.cur-year,'
        . '.legalpro-flatpickr-dark .flatpickr-current-month .flatpickr-monthDropdown-months,'
        . '.legalpro-flatpickr-dark .flatpickr-current-month input.cur-year{color:#f1f5f9!important;background:#1e293b;border:1px solid rgba(255,255,255,.14);}'
        . 'body.legalpro-dark-mode .flatpickr-current-month .flatpickr-monthDropdown-months option,'
        . '.legalpro-flatpickr-dark .flatpickr-current-month .flatpickr-monthDropdown-months option{background:#1e293b;color:#f1f5f9;}'
        . 'body.legalpro-dark-mode .flatpickr-months .flatpickr-prev-month,'
        . 'body.legalpro-dark-mode .flatpickr-months .flatpickr-next-month,'
        . '.legalpro-flatpickr-dark .flatpickr-months .flatpickr-prev-month,'
        . '.legalpro-flatpickr-dark .flatpickr-months .flatpickr-next-month{color:#e2e8f0;fill:#e2e8f0;}'
        . 'body.legalpro-dark-mode .flatpickr-months .flatpickr-prev-month svg path,'
        . 'body.legalpro-dark-mode .flatpickr-months .flatpickr-next-month svg path,'
        . '.legalpro-flatpickr-dark .flatpickr-months .flatpickr-prev-month svg path,'
        . '.legalpro-flatpickr-dark .flatpickr-months .flatpickr-next-month svg path{fill:#e2e8f0;}'
        . 'body.legalpro-dark-mode span.flatpickr-weekday,.legalpro-flatpickr-dark span.flatpickr-weekday{color:#94a3b8;}'
        . 'body.legalpro-dark-mode .flatpickr-day,.legalpro-flatpickr-dark .flatpickr-day{color:#e2e8f0;}'
        . 'body.legalpro-dark-mode .flatpickr-day.prevMonthDay,'
        . 'body.legalpro-dark-mode .flatpickr-day.nextMonthDay,'
        . '.legalpro-flatpickr-dark .flatpickr-day.prevMonthDay,'
        . '.legalpro-flatpickr-dark .flatpickr-day.nextMonthDay{color:#64748b;}'
        . 'body.legalpro-dark-mode .flatpickr-day:hover,'
        . 'body.legalpro-dark-mode .flatpickr-day:focus,'
        . '.legalpro-flatpickr-dark .flatpickr-day:hover,'
        . '.legalpro-flatpickr-dark .flatpickr-day:focus{background:rgba(94,114,228,.22);border-color:rgba(94,114,228,.35);}'
        . 'body.legalpro-dark-mode .flatpickr-day.today,.legalpro-flatpickr-dark .flatpickr-day.today{border-color:#5e72e4;}'
        . 'body.legalpro-dark-mode .flatpickr-day.selected,.legalpro-flatpickr-dark .flatpickr-day.selected{background:#5e72e4;border-color:#5e72e4;color:#fff;}'
        . 'body.legalpro-dark-mode .flatpickr-day.flatpickr-disabled,.legalpro-flatpickr-dark .flatpickr-day.flatpickr-disabled{color:#64748b;opacity:.45;}'
        . 'body.legalpro-dark-mode .flatpickr-day.legalpro-day-unavailable,'
        . 'body.legalpro-dark-mode .flatpickr-day.flatpickr-disabled.legalpro-day-unavailable,'
        . '.legalpro-flatpickr-dark .flatpickr-day.legalpro-day-unavailable,'
        . '.legalpro-flatpickr-dark .flatpickr-day.flatpickr-disabled.legalpro-day-unavailable{color:#64748b!important;opacity:.45;}'
        . '</style>';
}

function legalpro_render_availability_date_picker_script(): void
{
    static $rendered = false;
    if ($rendered) {
        return;
    }
    $rendered = true;

    echo '<script>'
        . '(function(){'
        . 'function formatFlatpickrDate(date){'
        . 'if(!(date instanceof Date)||isNaN(date.getTime())){return "";}'
        . 'var y=date.getFullYear();'
        . 'var m=String(date.getMonth()+1).padStart(2,"0");'
        . 'var d=String(date.getDate()).padStart(2,"0");'
        . 'return y+"-"+m+"-"+d;'
        . '}'
        . 'function getPickerAnchor(instance){'
        . 'if(!instance){return null;}'
        . 'return instance.altInput||instance._input||instance.input||null;'
        . '}'
        . 'function alignCalendarBelowInput(instance){'
        . 'if(!instance||!instance.calendarContainer){return;}'
        . 'var anchor=getPickerAnchor(instance);'
        . 'if(!anchor){return;}'
        . 'var cal=instance.calendarContainer;'
        . 'var rect=anchor.getBoundingClientRect();'
        . 'var calWidth=cal.offsetWidth||268;'
        . 'var left=Math.round(rect.left);'
        . 'var top=Math.round(rect.bottom+4);'
        . 'if(left+calWidth>window.innerWidth-8){left=Math.max(8,window.innerWidth-calWidth-8);}'
        . 'if(top+cal.offsetHeight>window.innerHeight-8){top=Math.max(8,Math.round(rect.top-cal.offsetHeight-4));}'
        . 'cal.classList.add("legalpro-calendar-below");'
        . 'cal.style.setProperty("position","fixed","important");'
        . 'cal.style.setProperty("left",left+"px","important");'
        . 'cal.style.setProperty("top",top+"px","important");'
        . 'cal.style.setProperty("right","auto","important");'
        . 'cal.style.setProperty("transform","none","important");'
        . 'cal.style.setProperty("margin","0","important");'
        . 'cal.style.zIndex="10050";'
        . '}'
        . 'function bindCalendarReposition(instance){'
        . 'if(!instance||instance._legalproRepositionBound){return;}'
        . 'instance._legalproReposition=function(){if(instance.isOpen){alignCalendarBelowInput(instance);}};'
        . 'window.addEventListener("scroll",instance._legalproReposition,true);'
        . 'window.addEventListener("resize",instance._legalproReposition);'
        . 'instance._legalproRepositionBound=true;'
        . '}'
        . 'function unbindCalendarReposition(instance){'
        . 'if(!instance||!instance._legalproRepositionBound){return;}'
        . 'window.removeEventListener("scroll",instance._legalproReposition,true);'
        . 'window.removeEventListener("resize",instance._legalproReposition);'
        . 'instance._legalproReposition=null;'
        . 'instance._legalproRepositionBound=false;'
        . '}'
        . 'window.LegalproAvailabilityDatePicker={'
        . 'instances:{},'
        . 'create:function(input,options){'
        . 'options=options||{};'
        . 'var el=typeof input==="string"?document.getElementById(input):input;'
        . 'if(!el||typeof flatpickr==="undefined"){return null;}'
        . 'var key=el.id||el.name||String(Math.random());'
        . 'if(this.instances[key]){unbindCalendarReposition(this.instances[key]);this.instances[key].destroy();delete this.instances[key];}'
        . 'var self=this;'
        . 'var wrap=el.closest(".ca-date-picker-wrap,.legalpro-date-picker-wrap")||el.parentElement;'
        . 'var usePositionBelow=options.positionBelow!==false;'
        . 'var fp=flatpickr(el,{'
        . 'minDate:options.minDate||"today",'
        . 'dateFormat:"Y-m-d",'
        . 'allowInput:false,'
        . 'static:false,'
        . 'disable:[function(date){return typeof options.isUnavailable==="function"?!!options.isUnavailable(date):false;}],'
        . 'onDayCreate:function(selectedDates,inputValue,instance,dayElem){'
        . 'if(typeof options.isUnavailable==="function"&&dayElem){'
        . 'var checkDate=(dayElem.dateObj instanceof Date&&!isNaN(dayElem.dateObj.getTime()))?dayElem.dateObj:null;'
        . 'if(checkDate&&options.isUnavailable(checkDate)){dayElem.classList.add("legalpro-day-unavailable");}'
        . 'else{dayElem.classList.remove("legalpro-day-unavailable");}'
        . '}'
        . 'if(typeof options.onDayCreate==="function"){options.onDayCreate(selectedDates,inputValue,instance,dayElem);}'
        . '},'
        . 'onReady:function(selectedDates,dateStr,instance){'
        . 'if(instance&&instance.calendarContainer){'
        . 'instance.calendarContainer.classList.toggle("legalpro-flatpickr-dark",document.body.classList.contains("legalpro-dark-mode"));'
        . '}'
        . 'if(typeof options.onReady==="function"){options.onReady(selectedDates,dateStr,instance);}'
        . '},'
        . 'onChange:function(selectedDates,dateStr){if(typeof options.onChange==="function"){options.onChange(selectedDates,dateStr);}},'
        . 'onOpen:function(selectedDates,dateStr,instance){'
        . 'if(instance&&instance.calendarContainer){'
        . 'instance.calendarContainer.classList.toggle("legalpro-flatpickr-dark",document.body.classList.contains("legalpro-dark-mode"));'
        . '}'
        . 'if(usePositionBelow&&instance){'
        . 'var alignNow=function(){alignCalendarBelowInput(instance);};'
        . 'requestAnimationFrame(function(){alignNow();requestAnimationFrame(alignNow);});'
        . 'bindCalendarReposition(instance);'
        . '}'
        . 'if(typeof options.onOpen==="function"){options.onOpen(selectedDates,dateStr,instance);}'
        . '},'
        . 'onClose:function(selectedDates,dateStr,instance){'
        . 'if(instance){unbindCalendarReposition(instance);}'
        . 'if(typeof options.onClose==="function"){options.onClose(selectedDates,dateStr,instance);}'
        . '},'
        . 'appendTo:options.appendTo||(usePositionBelow?document.body:wrap)||undefined,'
        . 'defaultDate:options.defaultDate||el.value||null'
        . '});'
        . 'this.instances[key]=fp;'
        . 'return fp;'
        . '},'
        . 'refresh:function(input,options){'
        . 'options=options||{};'
        . 'var el=typeof input==="string"?document.getElementById(input):input;'
        . 'if(!el){return;}'
        . 'var fp=this.instances[el.id||el.name];'
        . 'if(!fp){return;}'
        . 'if(typeof options.isUnavailable==="function"){'
        . 'fp.set("disable",[function(date){return !!options.isUnavailable(date);}]);'
        . '}'
        . 'fp.redraw();'
        . '},'
        . 'rebuild:function(input,options){'
        . 'this.destroy(input);'
        . 'return this.create(input,options||{});'
        . '},'
        . 'clearIfUnavailable:function(input,isUnavailableFn){'
        . 'var el=typeof input==="string"?document.getElementById(input):input;'
        . 'if(!el||typeof isUnavailableFn!=="function"||!el.value){return;}'
        . 'var parts=el.value.split("-");'
        . 'if(parts.length<3){return;}'
        . 'var dateObj=new Date(parseInt(parts[0],10),parseInt(parts[1],10)-1,parseInt(parts[2],10));'
        . 'if(isUnavailableFn(dateObj)){'
        . 'var fp=this.instances[el.id||el.name];'
        . 'if(fp){fp.clear();}else{el.value="";}'
        . '}'
        . '},'
        . 'destroy:function(input){'
        . 'var el=typeof input==="string"?document.getElementById(input):input;'
        . 'if(!el){return;}'
        . 'var key=el.id||el.name;'
        . 'if(this.instances[key]){unbindCalendarReposition(this.instances[key]);this.instances[key].destroy();delete this.instances[key];}'
        . '},'
        . 'formatDate:formatFlatpickrDate'
        . '};'
        . '})();'
        . '</script>';
}
